name: weather
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  firebase_core: ^2.15.0
  dio: ^5.3.2
  get_it: ^7.6.0
  injectable: ^2.1.2
  geolocator: ^9.0.2
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  injectable_generator: ^2.1.6
  mockito: ^5.4.2




flutter:
  uses-material-design: true

  assets:
    - assets/image/maxTemp.png
    - assets/image/minTemp.png
    - assets/image/humidity.png
    - assets/image/windVelocity.png
    - assets/image/sun.png


