// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVeuOGkGjJ2ez8hX6eBR447AkGFQJWh4w',
    appId: '1:730032771072:web:d3d8dfcc9ea200305d08e5',
    messagingSenderId: '730032771072',
    projectId: 'weather-2fad1',
    authDomain: 'weather-2fad1.firebaseapp.com',
    storageBucket: 'weather-2fad1.appspot.com',
    measurementId: 'G-S7C0CJ4T19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHoWfIxXTy-31ZCBwhL--TiJ3qwaot5kc',
    appId: '1:730032771072:android:4afbc3ac563ae2835d08e5',
    messagingSenderId: '730032771072',
    projectId: 'weather-2fad1',
    storageBucket: 'weather-2fad1.appspot.com',
  );
}
